name: PyTest

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Running the tests with PyTest
      run: |
        python -m pytest --import-mode=append tests/

